[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picklevw"
version = "0.1.0"
description = "A reader + GUI for pickle files using Pandas and Tkinter."
authors = [
    { name = "Jonathan Ciapetti", email = "jonathan.ciapetti@normabytes.com" }
]
license = { file = "LICENSE.txt" }
readme = "README.md"
requires-python = ">=3.6"
keywords = ["pickle", "GUI", "pandas", "tkinter"]

[project.urls]
Homepage = "https://github.com/jonathanciapetti/picklevw"

[project.dependencies]
pandas = ">=1.5"
prettyprinter = "*"
tkinter = "*"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package_data]
"picklevw" = ["*.py"]
